
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abozen
 */
public class fMenu extends javax.swing.JFrame {

    /**
     * Creates new form fMenu
     */
    
    int userNo = 0;
   
    public fMenu() {
        initComponents();
    }
    public fMenu(int userNo){
        initComponents();
        
        this.userNo = userNo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu_b2 = new javax.swing.JButton();
        menu_b1 = new javax.swing.JButton();
        menu_b3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_m1 = new javax.swing.JMenu();
        menu_m2 = new javax.swing.JMenu();
        menu_m3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_b2.setText("Send a New Mail");
        menu_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_b2ActionPerformed(evt);
            }
        });
        jPanel1.add(menu_b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, 50));

        menu_b1.setText("Mail Box");
        menu_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_b1ActionPerformed(evt);
            }
        });
        jPanel1.add(menu_b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 50));

        menu_b3.setText("Exit");
        menu_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_b3ActionPerformed(evt);
            }
        });
        jPanel1.add(menu_b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 100, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 480));

        jMenu1.setText("Menu");

        menu_m1.setText("Mail Box");
        jMenu1.add(menu_m1);

        menu_m2.setText("Send Mail");
        jMenu1.add(menu_m2);

        menu_m3.setText("Exit");
        jMenu1.add(menu_m3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_b3ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,"Sure? You want to exit?", "Swing Tester",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
               fLogin flogin = new fLogin();
               flogin.setVisible(true);
               this.dispose();
            }else if (result == JOptionPane.NO_OPTION){
               
            }else {
               
            }
        
    }//GEN-LAST:event_menu_b3ActionPerformed

    private void menu_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_b2ActionPerformed
        // TODO add your handling code here:
        fSend fsend = new fSend(userNo);
        fsend.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_b2ActionPerformed

    private void menu_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_b1ActionPerformed
        // TODO add your handling code here:
        fMailBox fmailbox = new fMailBox(userNo);
        fmailbox.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu_b1;
    private javax.swing.JButton menu_b2;
    private javax.swing.JButton menu_b3;
    private javax.swing.JMenu menu_m1;
    private javax.swing.JMenu menu_m2;
    private javax.swing.JMenu menu_m3;
    // End of variables declaration//GEN-END:variables
}
