/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abozen
 */
public class fRead extends javax.swing.JFrame {

    /**
     * Creates new form fRead
     */
    String mail = "";
    String topic = "";
    String sender = "";
    int userNo = 0;
    
    public fRead() {
        initComponents();
    }
    
    public fRead(int userNo, String mail, String topic, String sender){
        initComponents();
        
        this.userNo = userNo;
        this.mail = mail;
        this.sender = sender;
        this.topic = topic;
        
        setMails(mail, topic, sender);
    }
    
    public void setMails(String mail, String topic, String sender){
        read_txt1.setText(sender);
        read_txt2.setText(topic);
        read_txta.setText(mail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        read_txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        read_b1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        read_txta = new javax.swing.JTextArea();
        read_txt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        read_txt1.setEditable(false);
        jPanel1.add(read_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 290, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Sender");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 20));

        read_b1.setText("Back");
        read_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_b1ActionPerformed(evt);
            }
        });
        jPanel1.add(read_b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        read_txta.setEditable(false);
        read_txta.setColumns(20);
        read_txta.setRows(5);
        jScrollPane2.setViewportView(read_txta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 380, 300));

        read_txt2.setEditable(false);
        jPanel1.add(read_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 290, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Topic");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 60, 20));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void read_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_b1ActionPerformed
        // TODO add your handling code here:
        fMailBox fmailbox = new fMailBox(userNo);
        fmailbox.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_read_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fRead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton read_b1;
    private javax.swing.JTextField read_txt1;
    private javax.swing.JTextField read_txt2;
    private javax.swing.JTextArea read_txta;
    // End of variables declaration//GEN-END:variables
}
