

import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abozen
 */
public class fSend extends javax.swing.JFrame {

    /**
     * Creates new form fSend
     */
    
    int userNo = 0;
    
    public fSend() {
        initComponents();
    }
    public fSend(int userNo){
        initComponents();
        
        this.userNo = userNo;
    }
    
    public int setMailNo(){
        int ret = 0;
        try{
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","369874125");
            Statement st = con.createStatement();
            
            String query2 = "SELECT MAX(mailNo) FROM asd.mails";
            ResultSet rs = st.executeQuery(query2);
            while(rs.next()){
                ret = rs.getInt(1) + 1;
            }
            
        }catch(HeadlessException | SQLException E){
            JOptionPane.showMessageDialog(null,E );
        }
        
        return ret;
    }
    
    public boolean isMailExists(String mail){
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "369874125");
            Statement st = con.createStatement();

            String query = "SELECT * FROM asd.users WHERE email='" + mail + "' ";

            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                return true;
            } else {
                return false;
            }

        } catch (HeadlessException | SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        send_txt1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        send_txta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        send_txt2 = new javax.swing.JTextField();
        send_b1 = new javax.swing.JButton();
        send_b2 = new javax.swing.JButton();
        send_sp1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Reciever");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 30));
        jPanel1.add(send_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 330, 30));

        send_txta.setColumns(20);
        send_txta.setRows(5);
        jScrollPane1.setViewportView(send_txta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 330, 160));

        jLabel2.setText("Topic");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, 30));
        jPanel1.add(send_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 330, 30));

        send_b1.setText("Send");
        send_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_b1ActionPerformed(evt);
            }
        });
        jPanel1.add(send_b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 90, 30));

        send_b2.setText("Back");
        send_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_b2ActionPerformed(evt);
            }
        });
        jPanel1.add(send_b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        send_sp1.setModel(new javax.swing.SpinnerNumberModel(15, 10, 20, 1));
        send_sp1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                send_sp1StateChanged(evt);
            }
        });
        send_sp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send_sp1MouseClicked(evt);
            }
        });
        jPanel1.add(send_sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel3.setText("Font Size");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_b2ActionPerformed
        // TODO add your handling code here:
        fMenu fmenu = new fMenu(userNo);
        fmenu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_send_b2ActionPerformed

    private void send_sp1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_send_sp1StateChanged
        // TODO add your handling code here:
        send_txta.setFont(new Font("TimesRoman", Font.PLAIN, (Integer) send_sp1.getValue()));
    }//GEN-LAST:event_send_sp1StateChanged

    private void send_sp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_sp1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_send_sp1MouseClicked

    private void send_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_b1ActionPerformed
        // TODO add your handling code here:
        if(isMailExists(send_txt1.getText()))
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","369874125");
            Statement st = con.createStatement();
            Statement st2 = con.createStatement();
            
            
            String queryGet = "SELECT userNo FROM asd.users WHERE email='"+ send_txt1.getText() +"' ";
            ResultSet rs = st.executeQuery(queryGet);
            int recieverno = 3;
            while(rs.next()){
                recieverno = rs.getInt(1);
            }
            
            String query = "INSERT INTO asd.mails (senderNo, recieverNo, topic, mail, fontSize, mailNo) VALUES ("
                    + " '"+ userNo +"', "
                    + " '"+ recieverno +"', "
                    + " '"+ send_txt2.getText() +"', "
                    + " '"+ send_txta.getText() +"', "
                    + " '"+ send_sp1.getValue() +"' ,"
                    + " '"+ setMailNo() +"' )";

            st.execute(query);
            
            JOptionPane.showMessageDialog(null,"The mail is successfully sent." );
            
        }catch(HeadlessException | SQLException E){
            JOptionPane.showMessageDialog(null,E );
        }
        else
            JOptionPane.showMessageDialog(null,"This mail doesn't exists." );
    }//GEN-LAST:event_send_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fSend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send_b1;
    private javax.swing.JButton send_b2;
    private javax.swing.JSpinner send_sp1;
    private javax.swing.JTextField send_txt1;
    private javax.swing.JTextField send_txt2;
    private javax.swing.JTextArea send_txta;
    // End of variables declaration//GEN-END:variables
}
